/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LayoutImport } from './routes/_layout'
import { Route as LayoutIndexImport } from './routes/_layout/index'
import { Route as LayoutSavedImport } from './routes/_layout/saved'
import { Route as LayoutHistoryImport } from './routes/_layout/history'
import { Route as LayoutFavoritesImport } from './routes/_layout/favorites'

// Create/Update Routes

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const LayoutIndexRoute = LayoutIndexImport.update({
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutSavedRoute = LayoutSavedImport.update({
  path: '/saved',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutHistoryRoute = LayoutHistoryImport.update({
  path: '/history',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutFavoritesRoute = LayoutFavoritesImport.update({
  path: '/favorites',
  getParentRoute: () => LayoutRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/_layout/favorites': {
      preLoaderRoute: typeof LayoutFavoritesImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/history': {
      preLoaderRoute: typeof LayoutHistoryImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/saved': {
      preLoaderRoute: typeof LayoutSavedImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/': {
      preLoaderRoute: typeof LayoutIndexImport
      parentRoute: typeof LayoutImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  LayoutRoute.addChildren([
    LayoutFavoritesRoute,
    LayoutHistoryRoute,
    LayoutSavedRoute,
    LayoutIndexRoute,
  ]),
])

/* prettier-ignore-end */
